version: "2"

run:
  issues-exit-code: 1
  tests: true
  build-tags: ["whatsappmulti", "nomsteams"]
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - revive
    - fieldalignment
    - gocyclo
    - dupl
    - goconst
    - depguard
    - misspell
    - lll
    - unused
    - unparam
    - nakedret
    - prealloc
    - gocritic

  exclusions:
    paths:
      - gateway/bridgemap

  settings:
    dupl:
      threshold: 150
    goconst:
      min-len: 3
      min-occurrences: 3
    lll:
      line-length: 150
      tab-width: 1
    unparam:
      check-exported: false
    nakedret:
      max-func-lines: 0
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    gocritic:
      enabled-checks:
        - appendAssign
        - assignOp
        - boolExprSimplify
        - builtinShadow
        - captLocal
        - caseOrder
        - commentedOutImport
        - defaultCaseOrder
        - dupArg
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - elseif
        - emptyFallthrough
        - ifElseChain
        - importShadow
        - indexAlloc
        - methodExprCall
        - nestingReduce
        - offBy1
        - ptrToRefParam
        - regexpMust
        - singleCaseSwitch
        - sloppyLen
        - switchTrue
        - typeSwitchVar
        - typeUnparen
        - underef
        - unlambda
        - unnecessaryBlock
        - unslice
        - valSwap
        - wrapperFunc
        - yodaStyleExpr

output:
  format: colored-line-number
