version: "2"

run:
  issues-exit-code: 1
  tests: true
  build-tags: ["whatsappmulti", "nomsteams"]

linters:
  enable:
    - errcheck
    - govet
    - golint
    - gofmt
    - goimports
    - gocyclo
    - maligned
    - dupl
    - goconst
    - depguard
    - misspell
    - lll
    - unused
    - unparam
    - nakedret
    - prealloc
    - gocritic

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    govet:
      check-shadowing: true
    golint:
      min-confidence: 0.8
    gofmt:
      simplify: true
    goimports:
      local-prefixes: github.com
    gocyclo:
      min-complexity: 15
    maligned:
      suggest-new: true
    dupl:
      threshold: 150
    goconst:
      min-len: 3
      min-occurrences: 3
    depguard:
      list-type: blacklist
      include-go-root: false
    lll:
      line-length: 150
      tab-width: 1
    unused:
      check-exported: false
    unparam:
      check-exported: false
    nakedret:
      max-func-lines: 0
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    gocritic:
      enabled-checks:
        - appendAssign
        - assignOp
        - boolExprSimplify
        - builtinShadow
        - captLocal
        - caseOrder
        - commentedOutImport
        - defaultCaseOrder
        - dupArg
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - elseif
        - emptyFallthrough
        - ifElseChain
        - importShadow
        - indexAlloc
        - methodExprCall
        - nestingReduce
        - offBy1
        - ptrToRefParam
        - regexpMust
        - singleCaseSwitch
        - sloppyLen
        - switchTrue
        - typeSwitchVar
        - typeUnparen
        - underef
        - unlambda
        - unnecessaryBlock
        - unslice
        - valSwap
        - wrapperFunc
        - yodaStyleExpr
